config/routes.rb
Rails.application.routes.draw do
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :items,  only:   [:index, :show]
  resources :orders, only:   [:index, :show]
  resources :users,  only:   [:index, :show]
  resources :stores, only:   [:index, :show]

  root 'stores#index'
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :store

  has_many :order_items
  has_many :orders, through: :order_items
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :store

  has_many :order_items
  has_many :items, through: :order_items
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :item
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :user_roles
  has_many :users, through: :user_roles
end

app/models/store.rb
class Store < ActiveRecord::Base
  has_many :items
  has_many :orders
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  belongs_to :store
  has_many :orders

  has_many :user_roles
  has_many :roles, through: :user_roles

  def platform_admin?
    roles.exists?(name: 'platform_admin')
  end

  def store_admin?
    roles.exists?(name: 'store_admin')
  end

  def registered_user?
    roles.exists?(name: 'registered_user')
  end
end

app/models/user_role.rb
class UserRole < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authorize!

  add_flash_types :success, :info, :warning, :danger

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_permission
    @current_permission ||= PermissionsService.new(current_user)
  end

  def authorize!
    unless authorized?
      redirect_to root_url, danger:  "Danger Will Robinson"
    end
  end

  def authorized?
    current_permission.allow?(params[:controller], params[:action])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id].to_i)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, success: "Welcome to Storedom, #{user.name}"
    else
      flash.now[:danger] = "The username or password is invalid. Please try again."
      render :new
    end
  end

  def destroy
    session.clear

    redirect_to root_path, success: "You have been logged out."
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def index
    @stores = Store.all
  end

  def show
    @store = Store.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1><%= @items.count %> Items</h1>
    </div>
  </div>
  <div class="row"></div>
  <% @items.each do |item| %>
    <div class="col-sm-3">
      <h5><%= item.name %></h5>
      <%= link_to(image_tag(item.image_url), item_path(item)) %>
      <p>
        <%= item.description %>
      </p>
    </div>
  <% end %>
</div>

app/views/items/show.html.erb
<div class="container">
  <div class="row"></div>
  <div class="col-sm-3">
    <h5><%= @item.name %></h5>
    <%= image_tag(@item.image_url) %>
    <p>
      <%= @item.description %>
    </p>
  </div>
</div>

app/views/layouts/_guest_user_navbar.html.erb
<li>
  <%= link_to 'Stores', stores_path %>
</li>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <button class="navbar-toggle" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">Storedom</a>
  </div>
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <% if current_user && current_user.platform_admin? %>
        <%= render 'layouts/platform_admin_navbar' %>
      <% elsif current_user && current_user.store_admin? %>
        <%= render 'layouts/store_admin_navbar' %>
      <% else %>
        <%= render 'layouts/guest_user_navbar' %>
      <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <li>
          <%= link_to 'Logout', logout_path, method: :delete %>
        </li>
      <% else %>
        <li>
          <%= link_to 'Login', login_path %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_notices.html.erb
<% flash.each do |type, message| %>
  <div class="alert alert-<%= type %>"><%= message %></div>
<% end %>

app/views/layouts/_platform_admin_navbar.html.erb
<li>
  <%= link_to 'Item', items_path %>
</li>
<li>
  <%= link_to 'orders', orders_path %>
</li>
<li>
  <%= link_to 'Stores', stores_path %>
</li>

app/views/layouts/_store_admin_navbar.html.erb
<li>
  <%= link_to 'Item', items_path %>
</li>
<li>
  <%= link_to 'orders', orders_path %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
  <head>
    <title>Storedom</title>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/notices' %>
    <%= yield %>
  </body>
</html>

app/views/orders/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1><%= @orders.count %> Orders</h1>
    </div>
  </div>
  <div class="row"></div>
  <% @orders.each do |order| %>
    <div class="col-sm-12">
      <h2>Order <%= order.id %></h2>
      <h5>Client: <%= order.user.name %></h5>
      <h5>Order Items</h5>
      <% order.items.each_with_index do |item, index| %>
        <p>
          <%= "#{index + 1}. #{item.name}" %>
        </p>
      <% end %>
    </div>
  <% end %>
</div>

app/views/stores/index.html.erb
<div class="container">
  <div class="col-sm-12">
    <h1><%= @stores.count %> Stores</h1>
    <hr>
    <% @stores.each do |store| %>
      <h3><%= link_to store.name, store_path(store.id) %></h3>
      <h5>
        <%= store.items.count %> items,
        <%= store.orders.count %> orders,
        <%= store.users.count %> users
      </h5>
    <% end %>
  </div>
</div>

app/views/stores/show.html.erb
<div class="container">
  <div class="col-sm-12">
    <h1><%= @store.name %></h1>
    <hr>
    <% @store.items.each do |item| %>
      <div class="col-sm-3">
        <h5><%= item.name %></h5>
        <%= link_to(image_tag(item.image_url), item_path(item)) %>
        <p>
          <%= item.description %>
        </p>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1><%= @users.count %> Users</h1>
    </div>
  </div>
  <div class="row"></div>
  <% @users.each do |user| %>
    <div class="col-sm-12">
      <h2>User <%= user.id %></h2>
      <p><strong>Name:</strong> <%= user.name %></p>
      <p><strong>Email:</strong> <%= user.email %></p>
      <h5>Orders</h5>
      <% if user.orders.count > 0 %>
        <% user.orders.each_with_index do |order, index| %>
          <p>
            <%= "#{index + 1}. Order #{order.id}" %>
          </p>
        <% end %>
      <% else %>
        <p>This user doesn't have any orders.</p>
      <% end %>
    </div>
  <% end %>
</div>